config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'messages', to: "conversations#index"; 
  root to: 'pages#home'
  devise_for :users
  resources :users
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :avatar
         
         after_commit :add_default_avatar, on: %i[create update]
         has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

has_many :personal_messages, dependent: :destroy


         def avatar_thumbnail
          if(avatar.attached?)
            avatar.variant(resize:'150x150!').processed

          else 
            'default_profile.jpg'
        end 
      end 

      private 
      def add_default_avatar 
        unless avatar.attached? 
          avatar.attach(
            io: File.open(Rails.root.join(
              'app', 'assets', 'images', 'default_profile.jpg'
            )
          ), filename: 'default_profile.jpg', 
          content_type: 'image/jpg'
          )
      end 

    end 

    def name 
        email.split('@')[0]
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
    before_action :configure_permitted_parameters, 
    if: :devise_controller? 
        protected 
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys:[:avatar, :prenom, :nom, :metier, :localite, :telephone, :bio])
            devise_parameter_sanitizer.permit(:account_update, keys:[:avatar, :prenom, :localite, :bio])
        end 


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @freelancers = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def emojify(content)
        h(content).to_str.gsub(/:([\w+-]+):/) do |match|
          if emoji = Emoji.find_by_alias($1)
            %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
          else
            match
          end
        end.html_safe if content.present?
      end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gorgorlu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= render "layouts/nav/navigation" %>
    <%= yield %>
    <!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to "Gorgorlu",  root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
    <% if !current_user %>
      <li class="nav-item">
        <%= link_to 'Connexion', new_user_session_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
    <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete, class:"nav-link" %>
        <li class="nav-item">
        <%= link_to 'Modifier Compte', edit_user_registration_path, class: "nav-link"%>
</li>
      
    <% end %>
    </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  
</nav>

app/views/pages/home.html.erb
<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Trouvez ce qu'il vous faut</h1>
      <p>Gorgorlu est une platforme qui vous permet de trouver les meilleurs freelancers à Dakar</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Voir plus »</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
    </div>

    <hr>
    
  </div> <!-- /container -->
  <div class="freelancers-main">
    <h1>Nos freelancers</h1>
<div class="freelancers-container">
<% @freelancers.each do |freelancer| %>
<div class="freelancer card">
<%if freelancer.avatar.attached? %>
    <%= image_tag freelancer.avatar, class:"card-img", alt:'avatar' %>
    <% end %>
<div class="freelancer-info card-body">
<p> <%= freelancer.prenom %> <%= freelancer.nom %></p>
<p><%= freelancer.metier %></p>
   
            <%= link_to 'Voir Profil', user_path(freelancer), class: "btn btn-primary"%>


</div>
    
</div>

<% end %>

</div>
  </div>



</main>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Détails pour <%= @user.prenom %></h1>

<div class="user-details">
<div class="user-image">
<%= image_tag @user.avatar %>
</div>
<div class="user-details__content">
    <p>Prenom: <%= @user.prenom%></p>
    <p>Bio: <%= @user.bio %></p>
    <p>Compétences: </p>
    <%= link_to 'Envoyer message', new_personal_message_path(receiver_id: @user) %>
</div>
</div>